---
title: "04: MGIDI para seleção de genótipos de Linum usitatissimum no melhoramento genético vegetal"
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      comment = "##",
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE)

```


# Pacotes

```{r warning=FALSE, message=FALSE}
library(rio)
library(tidyverse)
library(factoextra)
library(metan)
library(DescTools)
library(pliman)

```


# Dados
```{r}
df <- 
  import("data/dados_capsulas.xlsx") |> 
  remove_rows_na() |> 
  mean_by(GEN)


```


# MGIDI
```{r}
mgidi_mod <- mgidi(df,
                   ideotype = c("h, h, h, h, 70, 50, 5, h, h"),
                   weights = c(3, 1, 1, 1, 2, 2, 2, 5, 5),
                   SI = 20)
plot(mgidi_mod, SI = 20)
ggsave("figs/mgidi.jpg",
       height = 5,
       width = 5)

export(list(
  mgidi = mgidi_mod$MGIDI,
  dif_sel = mgidi_mod$sel_dif,
  pca = mgidi_mod$PCA,
  loadings = mgidi_mod$finish_loadings
),
"data/mgidi.xlsx"
)

```

# Pontos fortes e fracos
```{r}
plot(mgidi_mod, type = "contribution")

mgidi_mod$contri_fac <- 
  mgidi_mod$contri_fac |> 
  mutate(across(contains("FA"), \(x){x - mean(x)}))
```


# Correlação
```{r}
corr_coef(df) |> 
  network_plot()

ggsave("figs/network.jpg")
```


# Section info
```{r}
sessionInfo()

```

